### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by wenLiangcan** [zohooo/jekyde#2]
Initializing default content folder...
Initializing default template folder...

Your website has been successfully generated in 0.123 seconds

/usr/lib/node_modules/jekyde/node_modules/express/lib/express.js:89
      throw new Error('Most middleware (like ' + name + ') is no longer bundle
            ^
Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/usr/lib/node_modules/jekyde/node_modules/express/lib/express.js:89:13)
    at Object.start (/usr/lib/node_modules/jekyde/server/server.js:27:21)
    at runServer (/usr/lib/node_modules/jekyde/builder/builder.js:184:12)
    at /usr/lib/node_modules/jekyde/builder/builder.js:230:9
    at /usr/lib/node_modules/jekyde/node_modules/async/lib/async.js:254:17
    at /usr/lib/node_modules/jekyde/node_modules/async/lib/async.js:157:25
    at /usr/lib/node_modules/jekyde/node_modules/async/lib/async.js:251:21
    at /usr/lib/node_modules/jekyde/node_modules/async/lib/async.js:615:34
    at /usr/lib/node_modules/jekyde/node_modules/async/lib/async.js:254:17
    at /usr/lib/node_modules/jekyde/node_modules/async/lib/async.js:157:25

**Comment by zohooo** [comment]
已修复，请更新到最新版本。
